-- 1. 지역별 부서의 수를 조회한다. (부서가 없으면 부서의 수는 0으로 조회한다.)
SELECT L.CITY
     , COUNT(D.DEPARTMENT_ID)
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
    ON D.LOCATION_ID = L.LOCATION_ID 
 GROUP BY L.CITY 
 ORDER BY L.CITY ASC
;

-- 2. 지역별 사원의 평균월급을 조회한다. (사원이 없으면 평균월급은 0으로 조회한다.)
SELECT L.CITY
	 , NVL(AVG(E.SALARY), 0)
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
    ON L.LOCATION_ID = D.LOCATION_ID 
  LEFT OUTER JOIN EMPLOYEES E 
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 GROUP BY L.CITY
 ORDER BY L.CITY ASC
;

-- 3. 도시명 별 사원의 수를 도시명으로 오름차순 정렬하여 조회한다.(사원이 없으면 사원의 수는 0으로 조회한다.)
SELECT L.CITY
     , COUNT(E.EMPLOYEE_ID)
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
    ON L.LOCATION_ID = D.LOCATION_ID 
  LEFT OUTER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY L.CITY 
 ORDER BY L.CITY ASC
;



-- 4. 모든 사원들의 현재 직무명과 과거의 직무명을 조회한다. 만약 직무가 한번도 변경되지 않았다면, 과거의 직무명은 '없음' 으로 조회한다.
SELECT E.EMPLOYEE_ID
     , JH.EMPLOYEE_ID 
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
;

-- 사원번호별 현재 직무명 오름차순
SELECT E.EMPLOYEE_ID
     , J.JOB_TITLE
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
 ORDER BY E.EMPLOYEE_ID ASC
;

-- 사원번호별 과거 직무명 오름차순
SELECT E.EMPLOYEE_ID
     , PJ.JOB_TITLE
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  LEFT OUTER JOIN JOBS PJ
    ON JH.JOB_ID = PJ.JOB_ID
 ORDER BY E.EMPLOYEE_ID ASC
;--INNER JOIN사용 ==> 있는값만나옴.

SELECT E.EMPLOYEE_ID
     , PJ.JOB_TITLE
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  LEFT OUTER JOIN JOBS PJ
    ON JH.JOB_ID = PJ.JOB_ID
 ORDER BY E.EMPLOYEE_ID ASC
;--OUTER JOIN 사용 ==> 없는값도 나옴.

SELECT E.EMPLOYEE_ID
     , J.JOB_TITLE AS 현재_직무명
     , (CASE 
     	   WHEN PJ.JOB_TITLE IS NULL THEN '없음'
     	   ELSE PJ.JOB_TITLE
        END) AS 과거_직무명
     --, NVL(PJ.JOB_TITLE, '없음') AS 과거_직무명
  FROM EMPLOYEES E
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
  LEFT OUTER JOIN JOB_HISTORY JH
    ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  LEFT OUTER JOIN JOBS PJ
    ON PJ.JOB_ID = JH.JOB_ID
 ORDER BY E.EMPLOYEE_ID ASC
;
-- INNER JOIN으로 EMPLOYEES와 JOBS를 연결 ==> J.JOB_TITLE 사용(현재 직무명)
-- LEFT OUTER JOIN 으로 EMPLOYEES에 과거직무형을 집어넣음(없는 값은 NULL)
-- CASE 사용해서 NULL을 없음으로, 값이 있으면 해당 값 출력되게